### ISSUE TITLE
Add a config parameter for the hyde.yml configuration

### ISSUE THREAD

**Issue by caendesilva** [hydephp/action#24]
```yaml
- name: Build and Deploy HydePHP Site
  uses: hydephp/action@master
    with:
      deploy-to: "pages"
      config:
        name: Example
        url: ${{ github.deployment.url }}
```

**Comment by caendesilva** [comment]
Array input not supported. https://stackoverflow.com/a/75420778/5700388

Would have to use this, which loses syntax highlighting, but could work:
```yaml
with:
  deploy-to: "artifact"
  config: |
    name: Example
    url: {{ github.deployment.url }}
```
