### ISSUE TITLE
Support array input for any arbitrary environment variables

### ISSUE THREAD

**Issue by caendesilva** [hydephp/action#43]
```yaml
- uses: hydephp/action@master
  with:
    deploy-to: "pages"
    env:
      FOO: bar
      SHA: ${{ github.sha }}
```
