### ISSUE TITLE
Update actions/upload-artifact from v3 to v4

### ISSUE THREAD

**Issue by sunderee** [hydephp/action#44]
## Issue description

This request comes after a Dependabot notified me to bump `actions/download-artifact` from v3 to v4.1.7:

> Versions of actions/download-artifact before 4.1.7 are vulnerable to arbitrary file write when downloading and extracting a specifically crafted artifact that contains path traversal filenames.

### Example

As per recommendation, I updated my GitHub Actions workflow file:

```yaml
name: Build and Deploy HydePHP Site to Deployment Branch

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build HydePHP Site
        uses: hydephp/action@master
        with:
          upload-artifact: true

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Deploy to deployment branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout --orphan deployment
          git rm -rf .
          mv build/* .
          git add .
          git commit -m "Deploy to deployment branch"
          git push -f origin deployment
```

### What happened

This will cause the `Download artifact` stage to fail.

```
Downloading single artifact
Error: Unable to download artifact(s): Artifact not found for name: build
        Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
        For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md
```

Upon inspection of which `actions/upload-artifact` version is used by this action, I discovered it's using v3 ([reference](https://github.com/hydephp/action/blob/cf8fd42473fc78116ea9530ddcf222a883d5c91f/action.yml#L140)).

## Proposed solution

If possible, update all actions that deal with uploading/downloading artifacts to use v4.
